import {Inter} from "next/font/google";
import "./styles/globals.scss";
import Header from "@/app/components/header/Header";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
  title: "Movies",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <NextTopLoader
      color="red"
      initialPosition={0.08}
      crawlSpeed={200}
      height={30}
      crawl={true}
      showSpinner={true}
      easing="ease"
      speed={200}
      shadow="0 0 10px #2299DD,0 0 5px #2299DD"
      template='<div class="bar" role="bar"><div class="peg"></div></div>
  <div class="spinner" role="spinner"><div class="spinner-icon"></div></div>'
      zIndex={1600}
      showAtBottom={false}
    />
    <div>
      <Header />
      {children}
    </div>
    </body>
    </html>
  );
}
