import { Inter } from "next/font/google";
import Header from "@/src/components/header/Header";
import "@/src/styles/globals.scss";
import "nprogress/nprogress.css";
import s from "./layout.module.scss";

const inter = Inter({subsets: ["latin"], weight: "400"});

export const metadata = {
  title: "The Movies Data Base ",
  description: "Generated by create next app",
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
}

export default function RootLayout({children}) {
  return (
    <html lang="en">
    <body className={inter.className}>
      <Header/>
      <div className={s.content}>
        {children}
      </div>
    </body>
    </html>
  );
}
